// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClxCz1Xa8d2IoCWph4f0dlsOLHmzMt3wY',
    appId: '1:409747472155:web:604c75a17fbf7724069dbe',
    messagingSenderId: '409747472155',
    projectId: 'blood-donation-app-f05ba',
    authDomain: 'blood-donation-app-f05ba.firebaseapp.com',
    storageBucket: 'blood-donation-app-f05ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7msXDF6yNMZV2BWJXPDH3m_sga7Z_EQ',
    appId: '1:409747472155:android:1da166250afbe0f2069dbe',
    messagingSenderId: '409747472155',
    projectId: 'blood-donation-app-f05ba',
    storageBucket: 'blood-donation-app-f05ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVlBri2PGrVk0TtOo5tttoxtieG3rZ9OE',
    appId: '1:409747472155:ios:67f9c97c1376793d069dbe',
    messagingSenderId: '409747472155',
    projectId: 'blood-donation-app-f05ba',
    storageBucket: 'blood-donation-app-f05ba.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVlBri2PGrVk0TtOo5tttoxtieG3rZ9OE',
    appId: '1:409747472155:ios:67f9c97c1376793d069dbe',
    messagingSenderId: '409747472155',
    projectId: 'blood-donation-app-f05ba',
    storageBucket: 'blood-donation-app-f05ba.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClxCz1Xa8d2IoCWph4f0dlsOLHmzMt3wY',
    appId: '1:409747472155:web:ff8a4c45351bfcc0069dbe',
    messagingSenderId: '409747472155',
    projectId: 'blood-donation-app-f05ba',
    authDomain: 'blood-donation-app-f05ba.firebaseapp.com',
    storageBucket: 'blood-donation-app-f05ba.appspot.com',
  );
}
